name: algorithms
description: Implementation of algorithms with Dart.
# version: 1.0.0
# homepage: https://www.example.com
# author: Mafinar K <mafinar@gmail.com>

environment:
  sdk: '>=2.13.0-0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.17.8
  extra_pedantic: 3.0.0
